build:
  environment:
    php: 7.0
  tests:
    override:
    - command: phpunit --coverage-clover=code-coverage
      coverage:
        file: code-coverage
        format: php-clover

filter:
  excluded_paths:
  - tests/*

checks:
  php:
    uppercase_constants: true
    use_self_instead_of_fqcn: true
    simplify_boolean_return: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    remove_extra_empty_lines: true
    align_assignments: false
    avoid_fixme_comments: true
    avoid_multiple_statements_on_same_line: true
    avoid_perl_style_comments: true
    avoid_todo_comments: true
    avoid_unnecessary_concatenation: true
    classes_in_camel_caps: true
    encourage_postdec_operator: true
    encourage_single_quotes: true
    fix_line_ending: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: true
      preserve_blanklines: true
      order_alphabetically: true
    function_in_camel_caps: true
    line_length:
      max_length: 120
    more_specific_types_in_doc_comments: true
    naming_conventions:
      local_variable: '^(?:[a-z][a-zA-Z0-9]*|_)$'
      abstract_class_name: '^[A-Z][a-zA-Z0-9]*$'
      utility_class_name: '^[A-Z][a-zA-Z0-9]*$'
      constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
      property_name: '^[a-z][a-zA-Z0-9]*$'
      method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
      parameter_name: '^[a-z][a-zA-Z0-9]*$'
      interface_name: '^[A-Z][a-zA-Z0-9]*$'
      type_name: '^[A-Z][a-zA-Z0-9]*$'
      exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
      isser_method_name: '^(?:is|has|should|may|supports)'
    newline_at_end_of_file: true
    no_goto: true
    no_long_variable_names:
      maximum: 22
    no_new_line_at_end_of_file: false
    no_short_method_names:
      minimum: 2
    no_short_variable_names:
      minimum: 2
    optional_parameters_at_the_end: true
    param_doc_comment_if_not_inferrable: true
    parameter_doc_comments: true
    parameters_in_camelcaps: true
    phpunit_assertions: true
    prefer_while_loop_over_for_loop: true
    properties_in_camelcaps: true

coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true
      other:
        after_type_cast: false
