language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
